development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DB'] || 'smartkarma_development' %>
  username: <%= ENV['POSTGRES_USER'] || 'smartkarma' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'smartkarma' %>
  host: <%= ENV['POSTGRES_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  reconnect: true

test:
  <<: *default
  database: smartkarma_test

production:
  <<: *default
  database: smartkarma_production
